Fix for invalid yaml config

diff --git a/root/start_nginx b/root/start_nginx
--- a/root/start_nginx
+++ b/root/start_nginx
@@ -88,23 +88,19 @@ generate_http_cfg() {
     local forcetls
     local hsts
     local hstssubs
-    local http="$1"
+    local http="${1// /_}"
     local http2
     local k=".http[\"$1\"]"
     local key
-    local loga
-    local loge
+    local loga="/nap/data/logs/${http,,}.access.log"
+    local loge="/nap/data/logs/${http,,}.error.log"
     local pki
     local server
     local sub
     local -a subs
-    local tmp
+    local title="$1"
+    local tmp="${title// /}"
     local ws
-
-    # Normalize
-    tmp="$(tr -d "[:punct:][:space:]" <<<"${http,,}")"
-    loga="/nap/data/logs/$tmp.access.log"
-    loge="/nap/data/logs/$tmp.error.log"
 
     subinfo "Creating $http Nginx http config"
 
@@ -167,7 +163,7 @@ generate_http_cfg() {
             subs+=("$sub")
         done < <(querystr "$k.subdomains[]?"); unset sub
 
-        [[ ${#subs[@]} -gt 0 ]] || subs+=("$tmp")
+        [[ ${#subs[@]} -gt 0 ]] || subs+=("${tmp,,}")
     fi
 
     # Determine server name from subs
@@ -178,8 +174,8 @@ generate_http_cfg() {
     [[ -n $server ]] || default="true"
 
     sed -r "/^\s*$/d" \
-        >"/nap/data/cfgs/http.d/${http// /_}.conf" <<EOF
-# $http
+        >"/nap/data/cfgs/http.d/${http,,}.conf" <<EOF
+# $title
 server {
   # HTTP ports
 ${enableIPv4:+  listen 80${default:+ default_server};}
@@ -389,7 +385,7 @@ generate_navdash() {
     local k
     local sub
 
-    case "$(head -n 1 www/index.html)" in
+    case "$(head -n 1 www/index.html 2>/dev/null)" in
         # echo -n "nap" | md5sum | awk '{print $1}'
         "4d3b2b4b063b4e4ae9cc04579c253c99") ;;
         *) return 0 ;;
@@ -446,9 +442,7 @@ EOF
 
             cert="$(querystr "$k.cert")"
             sub="$(querystr "$k.subdomains[0]")"
-
-            # Normalize
-            sub="$(tr -d "[:punct:][:space:]" <<<"${sub:-${http,,}}")"
+            sub="${sub:-${http// /}}"
 
             cat <<EOF
       <a href="" id="${http,,}">
@@ -460,7 +454,7 @@ EOF
       </a>
       <script>
         document.getElementById("${http,,}").setAttribute(
-          "href", "http${cert:+s}://$sub." + window.location.host
+          "href", "http${cert:+s}://${sub,,}." + window.location.host
         );
       </script>
 EOF
@@ -864,6 +858,7 @@ setup_nap
 # Read config from disk just once
 cfg="/nap/data/config.yaml"
 [[ -f "$cfg" ]] || errx 2 "$cfg not found"
+yq -M -o json "." "$cfg" || errx 3 "invalid yaml syntax"
 cfg="$(yq -M -o json "." "$cfg")"
 
 # Create missing certs
